// Code generated by "stringer -type=LinkMode -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LinkDown-0]
	_ = x[Link10HDX-1]
	_ = x[Link10FDX-2]
	_ = x[Link100HDX-3]
	_ = x[Link100FDX-4]
	_ = x[Link100T4-5]
	_ = x[Link1000HDX-6]
	_ = x[Link1000FDX-7]
	_ = x[Link2500FDX-8]
	_ = x[Link5GFDX-9]
	_ = x[Link10GFDX-10]
	_ = x[Link25GFDX-11]
	_ = x[Link40GFDX-12]
	_ = x[Link100GFDX-13]
}

const _LinkMode_name = "down10M-H10M-F100M-H100M-F100M-T41000M-H1000M-F2.5G-F5G-F10G-F25G-F40G-F100G-F"

var _LinkMode_index = [...]uint8{0, 4, 9, 14, 20, 26, 33, 40, 47, 53, 57, 62, 67, 72, 78}

func (i LinkMode) String() string {
	if i >= LinkMode(len(_LinkMode_index)-1) {
		return "LinkMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LinkMode_name[_LinkMode_index[i]:_LinkMode_index[i+1]]
}
