// Code generated by pioasm; DO NOT EDIT.

package main
import (
    pio "github.com/tinygo-org/pio/rp2040-pio"
)
// pulsar

const pulsarWrapTarget = 0
const pulsarWrap = 5

var pulsarInstructions = []uint16{
		//     .wrap_target
		0xe081, //  0: set    pindirs, 1                 
		0x80a0, //  1: pull   block                      
		0xa027, //  2: mov    x, osr                     
		0xe101, //  3: set    pins, 1                [1] 
		0xe000, //  4: set    pins, 0                    
		0x0043, //  5: jmp    x--, 3                     
		//     .wrap
}
const pulsarOrigin = -1
func pulsarProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+pulsarWrapTarget, offset+pulsarWrap)
	return cfg;
}

