// Code generated by pioasm; DO NOT EDIT.

//go:build rp2040
package piolib
import (
	pio "github.com/tinygo-org/pio/rp2-pio"
)
// hub75_row

const hub75_rowWrapTarget = 0
const hub75_rowWrap = 2

var hub75_rowInstructions = []uint16{
		//     .wrap_target
		0x7705, //  0: out    pins, 5         side 2 [7] 
		0x7f3b, //  1: out    x, 27           side 3 [7] 
		0x0042, //  2: jmp    x--, 2          side 0     
		//     .wrap
}
const hub75_rowOrigin = -1
func hub75_rowProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+hub75_rowWrapTarget, offset+hub75_rowWrap)
	cfg.SetSidesetParams(2, false, false)
	return cfg;
}

// hub75_data_rgb888

const hub75_data_rgb888WrapTarget = 0
const hub75_data_rgb888Wrap = 15

const hub75_data_rgb888offset_entry_point = 0
const hub75_data_rgb888offset_shift0 = 0
const hub75_data_rgb888offset_shift1 = 7

var hub75_data_rgb888Instructions = []uint16{
		//     .wrap_target
		0x80a0, //  0: pull   block           side 0     
		0x40e1, //  1: in     osr, 1          side 0     
		0x6068, //  2: out    null, 8         side 0     
		0x40e1, //  3: in     osr, 1          side 0     
		0x6068, //  4: out    null, 8         side 0     
		0x40e1, //  5: in     osr, 1          side 0     
		0x6060, //  6: out    null, 32        side 0     
		0x80a0, //  7: pull   block           side 0     
		0x50e1, //  8: in     osr, 1          side 1     
		0x7068, //  9: out    null, 8         side 1     
		0x50e1, // 10: in     osr, 1          side 1     
		0x7068, // 11: out    null, 8         side 1     
		0x50e1, // 12: in     osr, 1          side 1     
		0x7060, // 13: out    null, 32        side 1     
		0x507a, // 14: in     null, 26        side 1     
		0xb016, // 15: mov    pins, ::isr     side 1     
		//     .wrap
}
const hub75_data_rgb888Origin = -1
func hub75_data_rgb888ProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+hub75_data_rgb888WrapTarget, offset+hub75_data_rgb888Wrap)
	cfg.SetSidesetParams(1, false, false)
	return cfg;
}

