// Code generated by pioasm; DO NOT EDIT.

//go:build rp2040 || rp2350
package piolib
import (
	pio "github.com/tinygo-org/pio/rp2-pio"
)
// i2s

const i2sWrapTarget = 0
const i2sWrap = 7

const i2soffset_entry_point = 7

var i2sInstructions = []uint16{
		//     .wrap_target
		0x7001, //  0: out    pins, 1         side 2     
		0x1840, //  1: jmp    x--, 0          side 3     
		0x6001, //  2: out    pins, 1         side 0     
		0xe82e, //  3: set    x, 14           side 1     
		0x6001, //  4: out    pins, 1         side 0     
		0x0844, //  5: jmp    x--, 4          side 1     
		0x7001, //  6: out    pins, 1         side 2     
		0xf82e, //  7: set    x, 14           side 3     
		//     .wrap
}
const i2sOrigin = -1
func i2sProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+i2sWrapTarget, offset+i2sWrap)
	cfg.SetSidesetParams(2, false, false)
	return cfg;
}

