// Code generated by pioasm; DO NOT EDIT.

//go:build rp2350
package piolib
import (
    pio "github.com/tinygo-org/pio/rp2-pio"
)
// neosimple

const neosimpleWrapTarget = 0
const neosimpleWrap = 8

const neosimpleCyclesPerBit = 10
const neosimpleT1 = 2
const neosimpleT2 = 5
const neosimpleT3 = 3

var neosimpleInstructions = []uint16{
		//     .wrap_target
		0x8090, //  0: mov    osr, rxfifo[y]  side 0     
		0x6221, //  1: out    x, 1            side 0 [2] 
		0x1124, //  2: jmp    !x, 4           side 1 [1] 
		0x14e1, //  3: jmp    !osre, 1        side 1 [4] 
		0x04e1, //  4: jmp    !osre, 1        side 0 [4] 
		0x0080, //  5: jmp    y--, 0          side 0     
		0xef3f, //  6: set    x, 31           side 0 [15]
		0xef43, //  7: set    y, 3            side 0 [15]
		0x0f47, //  8: jmp    x--, 7          side 0 [15]
		//     .wrap
}
const neosimpleOrigin = -1
func neosimpleProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+neosimpleWrapTarget, offset+neosimpleWrap)
	cfg.SetSidesetParams(1, false, false)
	return cfg;
}

