// This file is autogenerated by pioasm version 2.2.0; do not edit!

//go:build rp2040 || rp2350
package piolib
import (
	pio "github.com/tinygo-org/pio/rp2-pio"
)
// parallel6

const parallel6WrapTarget = 0
const parallel6Wrap = 2

var parallel6Instructions = []uint16{
		//     .wrap_target
		0x6006, //  0: out    pins, 6         side 0
		0xb042, //  1: nop                    side 1
		0xa042, //  2: nop                    side 0
		//     .wrap
}
const parallel6Origin = -1
func parallel6ProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+parallel6WrapTarget, offset+parallel6Wrap)
	cfg.SetSidesetParams(1, false, false)
	return cfg;
}

