// Code generated by pioasm; DO NOT EDIT.

//go:build rp2040
package piolib
import (
    pio "github.com/tinygo-org/pio/rp2-pio"
)
// spi3w

const spi3wWrapTarget = 0
const spi3wWrap = 7

var spi3wInstructions = []uint16{
		//     .wrap_target
		0x6001, //  0: out    pins, 1         side 0     
		0x1040, //  1: jmp    x--, 0          side 1     
		0xe080, //  2: set    pindirs, 0      side 0     
		0xa042, //  3: nop                    side 0     
		0x5001, //  4: in     pins, 1         side 1     
		0x0084, //  5: jmp    y--, 4          side 0     
		0x20a0, //  6: wait   1 pin, 0        side 0     
		0xc000, //  7: irq    nowait 0        side 0     
		//     .wrap
}
const spi3wOrigin = -1
func spi3wProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+spi3wWrapTarget, offset+spi3wWrap)
	cfg.SetSidesetParams(1, false, false)
	return cfg;
}

