// Code generated by pioasm; DO NOT EDIT.

//go:build rp2040 || rp2350
package piolib
import (
    pio "github.com/tinygo-org/pio/rp2-pio"
)
// spi_cpha0

const spi_cpha0WrapTarget = 0
const spi_cpha0Wrap = 1

var spi_cpha0Instructions = []uint16{
		//     .wrap_target
		0x6101, //  0: out    pins, 1         side 0 [1] 
		0x5101, //  1: in     pins, 1         side 1 [1] 
		//     .wrap
}
const spi_cpha0Origin = -1
func spi_cpha0ProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+spi_cpha0WrapTarget, offset+spi_cpha0Wrap)
	cfg.SetSidesetParams(1, false, false)
	return cfg;
}

// spi_cpha1

const spi_cpha1WrapTarget = 0
const spi_cpha1Wrap = 2

var spi_cpha1Instructions = []uint16{
		//     .wrap_target
		0x6021, //  0: out    x, 1            side 0     
		0xb101, //  1: mov    pins, x         side 1 [1] 
		0x4001, //  2: in     pins, 1         side 0     
		//     .wrap
}
const spi_cpha1Origin = -1
func spi_cpha1ProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+spi_cpha1WrapTarget, offset+spi_cpha1Wrap)
	cfg.SetSidesetParams(1, false, false)
	return cfg;
}

