// Code generated by pioasm; DO NOT EDIT.

//go:build rp2040
package piolib
import (
    pio "github.com/tinygo-org/pio/rp2-pio"
)
// ws2812b_led

const ws2812b_ledWrapTarget = 0
const ws2812b_ledWrap = 7

const ws2812b_ledoffset_entry_point = 0

var ws2812b_ledInstructions = []uint16{
		//     .wrap_target
		0x80e0, //  0: pull   ifempty block              
		0xe001, //  1: set    pins, 1                    
		0x6041, //  2: out    y, 1                       
		0x0065, //  3: jmp    !y, 5                      
		0x0206, //  4: jmp    6                      [2] 
		0xe200, //  5: set    pins, 0                [2] 
		0xe000, //  6: set    pins, 0                    
		0x01e1, //  7: jmp    !osre, 1               [1] 
		//     .wrap
}
const ws2812b_ledOrigin = -1
func ws2812b_ledProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+ws2812b_ledWrapTarget, offset+ws2812b_ledWrap)
	return cfg;
}

