// Code generated by pioasm; DO NOT EDIT.

//go:build rp2350
package piolib
import (
    pio "github.com/tinygo-org/pio/rp2-pio"
)
// ws2812bfourpixels

const ws2812bfourpixelsWrapTarget = 0
const ws2812bfourpixelsWrap = 8

const ws2812bfourpixelsCyclesPerBit = 10
const ws2812bfourpixelsT1 = 2
const ws2812bfourpixelsT2 = 5
const ws2812bfourpixelsT3 = 3

var ws2812bfourpixelsInstructions = []uint16{
		//     .wrap_target
		0x8090, //  0: mov    osr, rxfifo[y]  side 0     
		0x6221, //  1: out    x, 1            side 0 [2] 
		0x1124, //  2: jmp    !x, 4           side 1 [1] 
		0x14e1, //  3: jmp    !osre, 1        side 1 [4] 
		0x04e1, //  4: jmp    !osre, 1        side 0 [4] 
		0x0080, //  5: jmp    y--, 0          side 0     
		0xef3f, //  6: set    x, 31           side 0 [15]
		0xef43, //  7: set    y, 3            side 0 [15]
		0x0f47, //  8: jmp    x--, 7          side 0 [15]
		//     .wrap
}
const ws2812bfourpixelsOrigin = -1
func ws2812bfourpixelsProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+ws2812bfourpixelsWrapTarget, offset+ws2812bfourpixelsWrap)
	cfg.SetSidesetParams(1, false, false)
	return cfg;
}

