// Code generated by pioasm; DO NOT EDIT.

//go:build rp2350
package main
import (
    pio "github.com/tinygo-org/pio/rp2-pio"
)
// rxfifoput

const rxfifoputWrapTarget = 4
const rxfifoputWrap = 7

var rxfifoputInstructions = []uint16{
		0xa0c3, //  0: mov    isr, null                  
		0xe043, //  1: set    y, 3                       
		0x8010, //  2: mov    rxfifo[y], isr             
		0x0082, //  3: jmp    y--, 2                     
		//     .wrap_target
		0xa02b, //  4: mov    x, !null                   
		0xa0c9, //  5: mov    isr, !x                    
		0x8018, //  6: mov    rxfifo[0], isr             
		0x0045, //  7: jmp    x--, 5                     
		//     .wrap
}
const rxfifoputOrigin = -1
func rxfifoputProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+rxfifoputWrapTarget, offset+rxfifoputWrap)
	return cfg;
}

