// Code generated by pioasm; DO NOT EDIT.

//go:build rp2350
package main
import (
    pio "github.com/tinygo-org/pio/rp2-pio"
)
// rxfifoputget

const rxfifoputgetWrapTarget = 0
const rxfifoputgetWrap = 1

var rxfifoputgetInstructions = []uint16{
		//     .wrap_target
		0x8018, //  0: mov    rxfifo[0], isr             
		0x8098, //  1: mov    osr, rxfifo[0]             
		//     .wrap
}
const rxfifoputgetOrigin = -1
func rxfifoputgetProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+rxfifoputgetWrapTarget, offset+rxfifoputgetWrap)
	return cfg;
}

